/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RestAssured;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.apache.http.HttpStatus;
import org.junit.BeforeClass;
import org.junit.Test;

import static io.restassured.RestAssured.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.notNullValue;
import static org.junit.Assert.*;

public class AppTest {
    @BeforeClass
    public static void setup(){
        //Mostrar detalhes quando o test falhar
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        //Caminhos base para acesso a API
        baseURI = "https://reqres.in";
        basePath = "/api";
    }
    @Test
    public void testDadosDoUsuario() {
        given().params("page", "2").
        when().
                get("/users").
        then().
                statusCode(HttpStatus.SC_OK).
                body("page", is(2)).
                body("data", is(notNullValue()));
    }
    @Test
    public void testCriarUsuario(){
        given().
                contentType(ContentType.JSON).
                body("{\"name\": \"diogo\",\"job\": \"leader\"}").
        when().
                post("/users").
        then().
                statusCode(HttpStatus.SC_CREATED).body("name", is("diogo"));
    }
}
