/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RestAssured.teste;

import RestAssured.dominio.User;
import io.restassured.http.ContentType;
import org.apache.http.HttpStatus;
import org.junit.Test;

import static io.restassured.RestAssured.given;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.notNullValue;

public class UserTest extends BaseTest{
    private static final String LIST_USERS_ENDPOINT = "/users";
    private static final String CREATE_USER_ENDPOINT = "/user";

    @Test
    public void testShowSpecificPage() {
        given().params("page", "2").
        when().
                get(LIST_USERS_ENDPOINT).
        then().
                statusCode(HttpStatus.SC_OK).
                body("page", is(2)).
                body("data", is(notNullValue()));
    }
    @Test
    public void testCreateUserSuccessfully(){
        User user = new User("diogo", "QA","diogo@gmai.com");
        given().
                contentType(ContentType.JSON).
                body(user).
        when().
                post(CREATE_USER_ENDPOINT).
        then().
                statusCode(HttpStatus.SC_CREATED).
                body("name", is("diogo"));
    }
}
