/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RestAssured.teste;

import RestAssured.dominio.Usuario;
import io.restassured.http.ContentType;
import org.apache.http.HttpStatus;
import org.junit.Test;

import static io.restassured.RestAssured.given;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.notNullValue;

public class UsuarioTeste extends BaseTest{
    private static final String LISTA_USUARIOS_ENDPOINT = "/users";
    private static final String CRIA_USUARIO_ENDPOINT = "/user";

    @Test
    public void testDadosDoUsuario() {
        given().params("page", "2").
        when().
                get(LISTA_USUARIOS_ENDPOINT).
        then().
                statusCode(HttpStatus.SC_OK).
                body("page", is(2)).
                body("data", is(notNullValue()));
    }
    @Test
    public void testCriarUsuario(){
        Usuario usuario = new Usuario("diogo", "QA","diogo@gmai.com");
        given().
                contentType(ContentType.JSON).
                body(usuario).
        when().
                post(CRIA_USUARIO_ENDPOINT).
        then().
                statusCode(HttpStatus.SC_CREATED).
                body("name", is("diogo"));
    }
}
